import React, { useEffect, useState } from "react";
import { session, signIn, signOut, useSession } from "next-auth/client";
import { getorderData } from "../../src/routes/order";
import { useRouter } from "next/router";
import Loader from "../components/Loader/Loader";
import Head from "next/head";
import Header from "../components/Header/Header";
import OrderItem from "../components/OrderItem/OrderItem";
import SigninPlease from "../components/SignInPlease/SigninPlease";
const Orders = ({ data }) => {
  const router = useRouter();
  const email = router.query.id;
  const [session, loading] = useSession();
  useEffect(async () => {}, [email]);
  return (
    <div style={{ marginTop: "6rem" }}>
      <Head>
        <title>Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <Header />
      <main className="container w-full sm:w-full md:w-2/3 lg:w-2/3 xl:w-2/3 2xl:w-2/3  mx-auto">
        {!session ? (
          <SigninPlease />
        ) : data === undefined ? (
          <Loader />
        ) : (
          <>
            <div className="top">
              <h1 className="text-left text-2xl my-4">Your Orders</h1>
            </div>
            <hr className="h-1 bg-red-500 w-full" />
            <div className="items">
              {data.map((item) => (
                <OrderItem key={item._id} data={item} />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default Orders;

export async function getServerSideProps(context) {
  const response = await getorderData("order/getorderdata", context.query.id);
  return {
    props: {
      data: response.data,
    },
  };
}
