import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "./components/Header/Header";
import Banner from "./components/Banner/Banner";
import ProductFeed from "./components/ProductFeed/ProductFeed";
import Footer from "./components/Footer/Footer";
import Script from "next/script";
function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <Script
        async
        src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.7.0/vanilla-tilt.min.js"
      ></Script>
      <Script
        async
        src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"
      ></Script>
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        {/* banner  */}
        <Banner />
        {/* productfeed */}
        {products !== undefined ? <ProductFeed products={products} /> : ""}

        {/* footer  */}
        <Footer />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  return {
    props: {
      products,
    },
  };
}

export default Home;
