import { useRouter } from "next/router";
import React from "react";
import Head from "next/head";
import Header from "./components/Header/Header";
import { useSelector } from "react-redux";
import { useSession } from "next-auth/client";
const Success = () => {
  const router = useRouter();
  const basket = useSelector((state) => state.basket);
  const [session, loading] = useSession();
  return (
    <div style={{ marginTop: "6rem" }}>
      <Head>
        <title>Order Confirmed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <main className="container">
        <Header />
        <div className="container h-60 w-2/3 block m-auto bg-white pt-5">
          <h2 className="text-center text-2xl h-20 font-bold">
            <span className="text-4xl mx-5 text-white rounded-lg h-20 bg-green-500">
              {" "}
              &#10003;
            </span>
            Thank You ! You Order has been confirmed
          </h2>
          <p className="text-center">
            Thanks for shopping with us. We'll send a confirmation once your
            item has shipped , if you would like to check the status of your
            order(s) please press the link below.
          </p>
          <button
            onClick={() => router.push(`/orders/${session.user.email}`)}
            className="bg-yellow-400 text-black font-bold w-96 border border-black border-2 m-auto my-5 py-3 block"
          >
            Go To Orders
          </button>
        </div>
      </main>
    </div>
  );
};

export default Success;
